#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Oct 27 16:13:07 2024

@author: legend
"""

import pandas as pd


import numpy as np

df = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie'],
    'ID': [1, 2, 3],
    'age': [25, None, 35],
    'city': ['NY', 'SF', 'LA']})
df2 = pd.DataFrame({'ID': [2, 3, 4], 'Score': [85, 95, 75]})
# df.index=['x', 'y', 'z']
# df.reset_index(drop=True, inplace=True)
# x=df.set_index("name", drop=False)
# # k=df.set_index(['name', 'city'], drop=False)
# k=df.set_index(['name', 'city'], inplace=True)

# print(df.loc['Alice','name'])

# df.dropna()
# df.loc[2, 'city'] = "JC"
# we=df["age"]
# df["age"]=df["age"]*2
# print(df.loc[1:2, "age":"city"])

rf= pd.merge(df, df2, how = "right" , on="ID")


# Print default NA value
print(df)
print("------------------------------------------------------------------------------")
print(df2)
# # print(df.isna())
print("------------------------------------------------------------------------------")
print(rf)
# print(df[["age", "city"]])

